project:
  type: website
  output-dir: docs

website:
  title: "Helen Seitzer"
  navbar:
    background: primary
    search: true
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "CV"

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual



